# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aae1f1b585958446aaa4d50e9d49fa3fce06a879b4525c3b127eecfd8910acd9743649b12d0b41f528d2daab4af5b9b65c7c34a933edd5eaa824ad74f2abc08

test:
  secret_key_base: 1ef7d5717b02a5d22e806afe39ac1b3ef12d126055ee69ed76807f0693c09d268d1cf1a1705911465888b741734f3067562a039bd4f253f2d9cd19b109b2e4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
